when:
  branch: ${CI_REPO_DEFAULT_BRANCH}

pipeline:
  ansible-lint:
    image: codeberg.org/6543/docker-images/ansible-lint
    group: lint
    commands:
      - ansible-galaxy install -r requirements.yml
      - ansible-lint
