# roles:

collections:
  - name: community.docker
    version: 4.8.1
  - name: hetzner.hcloud
    version: 5.3.1
  - name: community.crypto
    version: 3.0.4
  - name: community.dns
    version: 3.3.4
