---
# roles:

collections:
  - name: community.docker
    version: 4.7.0
  - name: hetzner.hcloud
    version: 5.2.0
  - name: community.crypto
    version: 3.0.3
  - name: community.dns
    version: 3.3.3
