# roles:

collections:
  - name: community.general
    version: 13.1.0
  - name: community.docker
    version: 5.2.1
  - name: hetzner.hcloud
    version: 6.10.0
  - name: community.crypto
    version: 3.3.0
  - name: community.dns
    version: 4.0.2
