# roles:

collections:
  - name: community.general
    version: 13.4.0
  - name: community.docker
    version: 5.4.0
  - name: hetzner.hcloud
    version: 7.2.0
  - name: community.crypto
    version: 3.5.0
  - name: community.dns
    version: 4.2.0
