# roles:

collections:
  - name: community.general
    version: 12.0.1
  - name: community.docker
    version: 5.0.3
  - name: hetzner.hcloud
    version: 6.2.1
  - name: community.crypto
    version: 3.0.5
  - name: community.dns
    version: 3.4.0
