# roles:

collections:
  - name: community.general
    version: 12.5.0
  - name: community.docker
    version: 5.2.0
  - name: hetzner.hcloud
    version: 6.8.0
  - name: community.crypto
    version: 3.1.1
  - name: community.dns
    version: 3.5.3
