---
# roles:

collections:
  - name: community.docker
    version: 3.13.1
  - name: hetzner.hcloud
    version: 4.2.0
  - name: community.crypto
    version: 2.22.0
  - name: community.dns
    version: 3.0.3
