---
# roles:

collections:
  - name: community.docker
    version: 4.4.0
  - name: hetzner.hcloud
    version: 4.2.2
  - name: community.crypto
    version: 2.25.0
  - name: community.dns
    version: 3.2.0
