# roles:

collections:
  - name: community.general
    version: 12.1.0
  - name: community.docker
    version: 5.0.5
  - name: hetzner.hcloud
    version: 6.3.0
  - name: community.crypto
    version: 3.0.5
  - name: community.dns
    version: 3.4.2
