# roles:

collections:
  - name: community.general
    version: 11.4.1
  - name: community.docker
    version: 4.8.2
  - name: hetzner.hcloud
    version: 5.4.0
  - name: community.crypto
    version: 3.0.5
  - name: community.dns
    version: 3.3.4
