# roles:

collections:
  - name: community.general
    version: 12.3.0
  - name: community.docker
    version: 5.0.6
  - name: hetzner.hcloud
    version: 6.7.0
  - name: community.crypto
    version: 3.1.0
  - name: community.dns
    version: 3.5.1
