---
# roles:

collections:
  - name: community.docker
    version: 3.11.0
  - name: hetzner.hcloud
    version: 4.0.1
  - name: community.crypto
    version: 2.21.0
  - name: community.dns
    version: 3.0.0
