---
# roles:

collections:
  - name: community.docker
    version: 4.5.1
  - name: hetzner.hcloud
    version: 4.2.2
  - name: community.crypto
    version: 2.26.0
  - name: community.dns
    version: 3.2.1
