---
# roles:

collections:
  - name: community.docker
    version: 4.0.1
  - name: hetzner.hcloud
    version: 4.2.2
  - name: community.crypto
    version: 2.22.3
  - name: community.dns
    version: 3.0.7
