- name: Setup main server at hetzner
  roles:
    - role: common
    - role: docker
    - role: docker_compose
    - role: caddy
    - role: woodpecker_server
    # - role: woodpecker_agent
    - role: woodpecker_autoscaler
    - role: weblate
