- name: Prepare Hetzner Cloud
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    hcloud_token: "{{ vault_hcloud_token }}"
  roles:
    - role: hetzner_firewalls
    # Create ci.woodpecker-ci.org server
    - role: ssh_key
      server_name: ci.woodpecker-ci.org
    - role: hetzner_server
      server_name: ci.woodpecker-ci.org
      hcloud_server_image: "ubuntu-20.04"
      hcloud_server_type: "cpx31"
      hcloud_server_location: "fsn1"

# https://stackoverflow.com/questions/29003420/reload-ansibles-dynamic-inventory#34012534
- name: Refresh inventory
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - meta: refresh_inventory
      tags:
        - always

- hosts: ci.woodpecker-ci.org
  vars:
    server_name: ci.woodpecker-ci.org
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_private_key_file: ./keys/{{ server_name | replace('.','_') }}.id_ed25519
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: common
    - role: docker
    - role: docker_compose
    - role: caddy
      caddy_version: 2.4.6-alpine
    - role: woodpecker_server
      woodpecker_version: &woodpecker_version next-1d6b073ca5
      woodpecker_host: https://{{ server_name }}
      woodpecker_orgs: woodpecker-ci
      woodpecker_admins: 6543,anbraten
      woodpecker_agent_secret: "{{ vault_woodpecker_agent_secret }}"
      woodpecker_github_client: "{{ vault_woodpecker_github_client }}"
      woodpecker_github_secret: "{{ vault_woodpecker_github_secret }}"
    - role: woodpecker_agent
      woodpecker_version: *woodpecker_version
      woodpecker_server: woodpecker-server:9000
      woodpecker_agent_secret: "{{ vault_woodpecker_agent1_secret }}"
      woodpecker_max_processes: 2
    - role: woodpecker_autoscaler
      woodpecker_version: next
      woodpecker_server: http://woodpecker-server:8000
      woodpecker_token: "{{ vault_woodpecker_api_token }}"
      woodpecker_min_agents: 0
      woodpecker_max_agents: 1
      woodpecker_workflows_per_agent: 2
      woodpecker_grpc_addr: grpc-ci.woodpecker-ci.org:443
      woodpecker_grpc_secure: true
      woodpecker_provider: hetzner
      woodpecker_hetzner_api_token: "{{ vault_hcloud_token }}"
      woodpecker_hetzner_server_type: cpx31
      woodpecker_hetzner_ssh_key_id: 4973153
    - role: weblate
      weblate_version: 4.13.1-2
      weblate_email_host: "{{ vault_weblate_email_host }}"
      weblate_email_use_ssl: 0
      weblate_email_use_tls: 1
      weblate_email_port: 587
      weblate_email_username: "{{ vault_weblate_email_username }}"
      weblate_email_password: "{{ vault_weblate_email_password }}"
      weblate_postgres_password: "{{ vault_weblate_postgres_password }}"
      weblate_domain: "translate.woodpecker-ci.org"
      weblate_admin_email: "{{ vault_weblate_admin_email }}"
      weblate_site_title: Woodpecker translate
