- name: Prepare Hetzner Cloud
  hosts: localhost
  connection: local
  become: no
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  vars:
    hcloud_token: "{{ vault_hcloud_token }}"
  roles:
    - role: hetzner-firewalls
    # Create ci.woodpecker-ci.org server
    - role: ssh-key
      server_name: ci.woodpecker-ci.org
    - role: hetzner-server
      server_name: ci.woodpecker-ci.org
      hcloud_server_image: "ubuntu-20.04"
      hcloud_server_type: "cpx31"
      hcloud_server_location: "fsn1"

# https://stackoverflow.com/questions/29003420/reload-ansibles-dynamic-inventory#34012534
- name: Refresh inventory
  hosts: localhost
  become: no
  gather_facts: false
  tasks:
    - meta: refresh_inventory
      tags:
        - always

- name: Prepare
  hosts: localhost
  connection: local
  become: no
  gather_facts: false
  vars:
    server_name: ci.woodpecker-ci.org
  vars_files:
    - group_vars/all/vault.yml
  tasks:
    - name: Open SSH in firewall
      hetzner.hcloud.hcloud_server:
        api_token: "{{ vault_hcloud_token }}"
        name: "{{ server_name }}"
        firewalls:
          - ssh
          - web
      delegate_to: localhost
      tags:
        - always
        - ssh-open
    - name: Waits until server is ready
      wait_for:
        host: "{{ server_name }}"
        port: 22
        delay: 2
        timeout: 60
      delegate_to: localhost
      tags:
        - always
        - ssh-open

- hosts: ci.woodpecker-ci.org
  vars:
    server_name: ci.woodpecker-ci.org
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_private_key_file: ./keys/{{ server_name | replace('.','_') }}.id_ed25519
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: common
    - role: docker
    - role: docker_compose
    - role: caddy
      caddy_version: 2.4.6-alpine
    - role: woodpecker
      woodpecker_version: next
      woodpecker_host: https://{{ server_name }}
      woodpecker_orgs: woodpecker-ci
      woodpecker_admins: 6543,anbraten
      woodpecker_github_client: "{{ vault_woodpecker_github_client }}"
      woodpecker_github_secret: "{{ vault_woodpecker_github_secret }}"
      woodpecker_agent_secret: "{{ vault_woodpecker_agent_secret }}"
      woodpecker_max_processes: 2
    - role: weblate
      weblate_version: 4.13.1-2
      weblate_email_host: "{{ vault_weblate_email_host }}"
      weblate_email_use_ssl: 0
      weblate_email_use_tls: 1
      weblate_email_port: 587
      weblate_email_username: "{{ vault_weblate_email_username }}"
      weblate_email_password: "{{ vault_weblate_email_password }}"
      weblate_postgres_password: "{{ vault_weblate_postgres_password }}"
      weblate_domain: "translate.woodpecker-ci.org"
      weblate_admin_email: "{{ vault_weblate_admin_email }}"
      weblate_site_title: Woodpecker translate

- name: Cleanup
  hosts: localhost
  connection: local
  become: no
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
  tasks:
    - name: Close SSH
      hetzner.hcloud.hcloud_server:
        api_token: "{{ vault_hcloud_token }}"
        name: ci.woodpecker-ci.org
        firewalls:
          - web
      tags:
        - always
        - ssh-close
      delegate_to: localhost
