# - name: Prepare Hetzner Cloud
#   hosts: localhost
#   connection: local
#   become: false
#   gather_facts: false
#   vars_files:
#     - group_vars/all/vault.yml
#   vars:
#     hcloud_token: "{{ vault_hcloud_token }}"
#   roles:
#     - role: hetzner_firewalls
#     # Create ci.woodpecker-ci.org server
#     - role: ssh_key
#       server_name: ci.woodpecker-ci.org
#     - role: hetzner_server
#       server_name: ci.woodpecker-ci.org
#       hcloud_server_image: "ubuntu-20.04"
#       hcloud_server_type: "cpx31"
#       hcloud_server_location: "fsn1"

- name: Setup main server at hetzner
  hosts: ci.woodpecker-ci.org
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: common
    - role: docker
    - role: docker_compose
    - role: caddy
      caddy_version: 2.4.6-alpine
    - role: woodpecker_server
      woodpecker_server_version: &woodpecker_version next-549d095ff3
      woodpecker_server_host: https://{{ inventory_hostname }}
      woodpecker_server_orgs: woodpecker-ci
      woodpecker_server_admins: 6543,anbraten
      woodpecker_server_agent_secret: "{{ vault_woodpecker_agent_secret }}"
      woodpecker_server_github_client: "{{ vault_woodpecker_github_client }}"
      woodpecker_server_github_secret: "{{ vault_woodpecker_github_secret }}"
    - role: woodpecker_agent
      woodpecker_agent_version: *woodpecker_version
      woodpecker_agent_server: woodpecker-server:9000
      woodpecker_agent_agent_secret: "{{ vault_woodpecker_agent1_secret }}"
      woodpecker_agent_max_processes: 2
    - role: woodpecker_autoscaler
      woodpecker_autoscaler_version: next
      woodpecker_autoscaler_server_url: http://woodpecker-server:8000
      woodpecker_autoscaler_server_token: "{{ vault_woodpecker_api_token }}"
      woodpecker_autoscaler_min_agents: 0
      woodpecker_autoscaler_max_agents: 1
      woodpecker_autoscaler_workflows_per_agent: 2
      woodpecker_autoscaler_grpc_addr: grpc-ci.woodpecker-ci.org:443
      woodpecker_autoscaler_grpc_secure: true
      woodpecker_autoscaler_provider: hetznercloud
      woodpecker_autoscaler_hetzner_api_token: "{{ vault_hcloud_token }}"
      woodpecker_autoscaler_hetzner_server_type: cpx41
      woodpecker_autoscaler_hetzner_ssh_keys: ci.woodpecker-ci.org-ssh
    - role: weblate
      weblate_version: 4.18.2.2
      weblate_email_host: "{{ vault_weblate_email_host }}"
      weblate_email_use_ssl: 0
      weblate_email_use_tls: 1
      weblate_email_port: 587
      weblate_email_username: "{{ vault_weblate_email_username }}"
      weblate_email_password: "{{ vault_weblate_email_password }}"
      weblate_postgres_password: "{{ vault_weblate_postgres_password }}"
      weblate_domain: "translate.woodpecker-ci.org"
      weblate_admin_email: "{{ vault_weblate_admin_email }}"
      weblate_site_title: Woodpecker translate
