- name: Create common docker network for reverse proxying
  community.docker.docker_network:
    name: web
  tags:
    - caddy

- name: Create Caddy directory
  ansible.builtin.file:
    path: /opt/caddy
    state: directory
    mode: '0o700'
  tags:
    - caddy

- name: Copy Caddy config
  ansible.builtin.copy:
    src: Caddyfile
    dest: /opt/caddy/Caddyfile
    mode: '0o644'
  register: caddy_output
  tags:
    - caddy

- name: Create Caddy data volume
  community.docker.docker_volume:
    name: caddy_data
  tags:
    - caddy

- name: Create Caddy config volume
  community.docker.docker_volume:
    name: caddy_config
  tags:
    - caddy

- name: Create Caddy container
  community.docker.docker_container:
    name: caddy
    hostname: caddy
    image: caddy:{{ caddy_version }}
    restart_policy: 'always'
    restart: true # To reload the Caddyfile in case the container wasn't updated
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - name: web
  tags:
    - caddy
