- name: Create volumes for containers
  community.docker.docker_volume:
    name: '{{ item }}'
  loop:
    - weblate_postgres-data
    - weblate_redis-data
    - weblate_weblate-data
  tags:
    - weblate

- name: Create Weblate network
  community.docker.docker_network:
    name: weblate
  tags:
    - weblate

- name: Create Weblate cache container
  community.docker.docker_container:
    name: weblate_cache
    hostname: weblate-cache
    # renovate: datasource=docker depName=docker.io/valkey/valkey
    image: docker.io/valkey/valkey:8-alpine
    restart_policy: 'always'
    command: [valkey-server, --save, '60', '1']
    volumes:
      - weblate_redis-data:/data
    networks:
      - name: weblate
  tags:
    - weblate

- name: Create Weblate database container
  community.docker.docker_container:
    name: weblate_database
    hostname: weblate-database
    # renovate: datasource=docker depName=library/postgres
    image: docker.io/postgres:18-alpine
    volumes:
      - weblate_postgres-data:/var/lib/postgresql/data
    restart_policy: 'always'
    networks:
      - name: weblate
    env:
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: '{{ weblate_postgres_password | string }}'
      POSTGRES_DATABASE: 'weblate'
      POSTGRES_HOST: 'database'
      POSTGRES_PORT: '5432'
  tags:
    - weblate

- name: Create Weblate container
  community.docker.docker_container:
    name: weblate
    hostname: weblate
    image: docker.io/weblate/weblate:{{ weblate_version }}
    restart_policy: 'always'
    volumes:
      - weblate_weblate-data:/app/data
    tmpfs:
      - /run
      - /tmp
    read_only: true
    networks:
      - name: weblate
      - name: web
    env:
      WEBLATE_EMAIL_HOST: '{{ weblate_email_host | string }}'
      WEBLATE_EMAIL_PORT: '{{ weblate_email_port | string }}'
      WEBLATE_EMAIL_USE_TLS: '{{ weblate_email_use_tls | string }}'
      WEBLATE_EMAIL_USE_SSL: '{{ weblate_email_use_ssl | string }}'
      WEBLATE_EMAIL_HOST_USER: '{{ weblate_email_username | string }}'
      WEBLATE_EMAIL_HOST_PASSWORD: '{{ weblate_email_password | string }}'
      WEBLATE_SERVER_EMAIL: '{{ weblate_email_username | string }}'
      WEBLATE_DEFAULT_FROM_EMAIL: '{{ weblate_email_username | string }}'
      WEBLATE_SITE_DOMAIN: '{{ weblate_domain | string }}'
      WEBLATE_ADMIN_EMAIL: '{{ weblate_admin_email | string }}'
      WEBLATE_SITE_TITLE: '{{ weblate_site_title | string }}'
      WEBLATE_IP_BEHIND_REVERSE_PROXY: 'True'
      WEBLATE_SECURE_PROXY_SSL_HEADER: 'HTTP_X_FORWARDED_PROTO,https'
      WEBLATE_ENABLE_HTTPS: 'True'
      WEBLATE_DEFAULT_COMMITER_EMAIL: 'woodpecker-bot@obermui.de'
      WEBLATE_DEFAULT_COMMITER_NAME: 'Woodpecker translate'
      WEBLATE_GPG_IDENTITY: 'Woodpecker translate <woodpecker-bot@obermui.de>'
      POSTGRES_USER: 'weblate'
      POSTGRES_PASSWORD: '{{ weblate_postgres_password | string }}'
      POSTGRES_DATABASE: 'weblate'
      POSTGRES_HOST: 'weblate-database'
      POSTGRES_PORT: '5432'
      REDIS_HOST: 'weblate-cache'
      REDIS_PORT: '6379'
  tags:
    - weblate
