- name: Create volumes for containers
  community.docker.docker_volume:
    name: '{{ item }}'
  loop:
    - weblate_postgres-data
    - weblate_redis-data
    - weblate_weblate-data

- name: Weblate cache container
  community.docker.docker_container:
    name: weblate_cache
    image: redis:{{ redis_version | string }}
    restart: true
    restart_policy: 'always'
    command: [redis-server, --save, '60', '1']
    volumes:
      - weblate_redis-data:/data
    networks:
      - name: web
  tags:
    - weblate
- name: Weblate database container
  community.docker.docker_container:
    name: weblate_database
    image: postgres:{{ postgres_version | string }}
    env:
      POSTGRES_USER: 'weblate'
      POSTGRES_PASSWORD: '{{ weblate_postgres_password | string }}'
      POSTGRES_DATABASE: 'weblate'
      POSTGRES_HOST: 'database'
      POSTGRES_PORT: '5432'
    volumes:
      - weblate_postgres-data:/var/lib/postgresql/data
    restart: true
    restart_policy: 'always'
    networks:
      - name: web
  tags:
    - weblate

- name: Weblate container
  community.docker.docker_container:
    name: weblate
    pull: 'always'
    image: weblate/weblate:{{ weblate_version }}
    volumes:
      - weblate_weblate-data:/app/data
    env:
      WEBLATE_EMAIL_HOST: '{{ weblate_email_host | string }}'
      WEBLATE_EMAIL_PORT: '{{ weblate_email_port | string }}'
      WEBLATE_EMAIL_USE_TLS: '{{ weblate_email_use_tls | string }}'
      WEBLATE_EMAIL_USE_SSL: '{{ weblate_email_use_ssl | string }}'
      WEBLATE_EMAIL_HOST_USER: '{{ weblate_email_username | string }}'
      WEBLATE_EMAIL_HOST_PASSWORD: '{{ weblate_email_password | string }}'
      WEBLATE_SERVER_EMAIL: '{{ weblate_email_username | string }}'
      WEBLATE_DEFAULT_FROM_EMAIL: '{{ weblate_email_username | string }}'
      WEBLATE_SITE_DOMAIN: '{{ weblate_domain | string }}'
      WEBLATE_ADMIN_EMAIL: '{{ weblate_admin_email | string }}'
      WEBLATE_SITE_TITLE: '{{ weblate_site_title | string }}'
      POSTGRES_USER: 'weblate'
      POSTGRES_PASSWORD: '{{ weblate_postgres_password | string }}'
      POSTGRES_DATABASE: 'weblate'
      POSTGRES_HOST: 'weblate_database'
      POSTGRES_PORT: '5432'
      REDIS_HOST: 'weblate_cache'
      REDIS_PORT: '6379'
    restart: true
    restart_policy: 'always'
    networks:
      - name: web

  tags:
    - weblate
