- name: Create Vaultwarden data volume
  community.docker.docker_volume:
    name: vaultwarden_data
  tags:
    - vaultwarden

- name: Create Vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    hostname: vaultwarden
    image: vaultwarden/server:{{ vaultwarden_version }}
    restart_policy: 'always'
    restart: true
    env:
      DOMAIN: 'https://vault.woodpecker-ci.org'
      SENDS_ALLOWED: 'false'
      SIGNUPS_ALLOWED: 'false'
      EMERGENCY_ACCESS_ALLOWED: 'false'
      ORG_CREATION_USERS: 'none'
      SMTP_HOST: '{{ vaultwarden_smtp_host | string }}'
      SMTP_PORT: '{{ vaultwarden_smtp_port | string }}'
      SMTP_SECURITY: '{{ vaultwarden_smtp_security | string }}'
      SMTP_FROM: '{{ vaultwarden_smtp_username | string }}'
      SMTP_USERNAME: '{{ vaultwarden_smtp_username | string }}'
      SMTP_PASSWORD: '{{ vaultwarden_smtp_password | string }}'
    volumes:
      - vaultwarden_data:/data
    networks:
      - name: web
  tags:
    - vaultwarden
