- name: Create a ssh key for {{ server_name }}
  hcloud_ssh_key:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}-ssh"
    public_key: "{{ lookup('file', './keys/{{ server_name | replace('.','_') }}.id_ed25519.pub') }}"
    state: present
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-server

- name: Create a server {{ server_name }}
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
    server_type: "{{ hcloud_server_type }}"
    location: "{{ hcloud_server_location }}"
    image: "{{ hcloud_server_image }}"
    state: present
    # firewalls:
      # - "{{ hcloud_firewall_ssh_only }}"
    ssh_keys:
      - "{{ server_name }}-ssh"
  delegate_to: localhost
  register: server
  tags:
    - hetzner
    - hetzner-server

- name: Waits until server is ready
  wait_for:
    host: "{{ server.hcloud_server.ipv4_address }}"
    port: 22
    delay: 2
    timeout: 60
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-server
