- name: create a ssh key for {{ server_name }}
  vars:
    key_path: "{{ './keys/%s.id_ed25519.pub' | format(server_name | replace('.','_')) }}"
  hetzner.hcloud.hcloud_ssh_key:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}-ssh"
    public_key: "{{ lookup('file', key_path) }}"
    state: present
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-server

- name: create a server {{ server_name }}
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
    server_type: "{{ hcloud_server_type }}"
    location: "{{ hcloud_server_location }}"
    image: "{{ hcloud_server_image }}"
    state: present
    # firewalls: {{ hcloud_firewalls.split(',') }}
    ssh_keys:
      - "{{ server_name }}-ssh"
  delegate_to: localhost
  register: server
  tags:
    - hetzner
    - hetzner-server

- name: Waits until server is ready
  wait_for:
    host: "{{ server.hcloud_server.ipv4_address }}"
    port: 22
    delay: 2
    timeout: 60
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-server
