- name: Setup dns
  community.dns.hetzner_dns_record_sets:
    hetzner_token: '{{ hetzner_dns_token }}'
    zone_name: woodpecker-ci.org
    prune: true # remove all records not defined in record_sets
    record_sets:
      - prefix: ''
        type: NS
        ignore: true

      - prefix: ''
        type: SOA
        ignore: true

      # website
      - type: A
        prefix: ''
        value:
          - 185.199.110.153
      - type: AAAA
        prefix: ''
        value:
          - 2606:50c0:8002::153
      - type: CNAME
        prefix: www
        value:
          - woodpecker-ci.github.io.

      # email
      - type: MX
        prefix: ''
        value:
          - 10 smtpin.rzone.de.
      - type: A
        prefix: autoconfig
        value:
          - 81.169.145.141
      - type: AAAA
        prefix: autoconfig
        value:
          - 2a01:238:20a:202:5800::1141
      - type: SRV
        prefix: _autodiscover._tcp.autoconfig
        value:
          - 0 0 443 autoconfigure.strato.de.

      # ci-server
      - type: A
        prefix: server01
        value:
          - 168.119.99.122
      - type: AAAA
        prefix: server01
        value:
          - 2a01:4f8:1c17:ef38::1
      - type: CNAME
        prefix: ci
        value:
          - server01.woodpecker-ci.org.
      - type: CNAME
        prefix: grpc-ci
        value:
          - server01.woodpecker-ci.org.
      - type: CNAME
        prefix: translate
        value:
          - server01.woodpecker-ci.org.
      - type: CNAME
        prefix: go
        value:
          - server01.woodpecker-ci.org.
  tags:
    - dns
