- name: Include tasks on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - docker

- name: Start Docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  tags:
    - docker
