- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - python-setuptools
  tags:
    - docker

- name: Add apt key for Docker repository
  ansible.builtin.apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: Add Docker repository (amd64)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_architecture == "x86_64"
  tags:
    - docker

- name: Add Docker repository (armhf)
  ansible.builtin.apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_architecture == "armv7l"
  tags:
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name: "docker-ce"
    update_cache: true
    force: true
  tags:
    - docker

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
  tags:
    - docker

- name: Install Python docker module for ansible
  ansible.builtin.pip:
    name: docker
    executable: pip3
  tags:
    - docker
