- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
  tags:
    - docker

- name: Add apt key for Docker repository
  ansible.builtin.apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: Add Docker repository (amd64)
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_architecture == "x86_64"
  tags:
    - docker

- name: Add Docker repository (armhf)
  ansible.builtin.apt_repository:
    repo: 'deb [arch=armhf signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_architecture == "armv7l"
  tags:
    - docker

- name: Add Docker repository (arm64)
  ansible.builtin.apt_repository:
    repo: 'deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_architecture == "aarch64"
  tags:
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - python3-docker
    update_cache: true
    force: true
  tags:
    - docker
