- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
  tags:
    - docker

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: [stable]
    architectures: "{{ docker_apt_arch[ansible_facts['architecture']] }}"
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true
  tags:
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - python3-docker
    update_cache: true
    force: true
  tags:
    - docker
