- name: Create a firewall for ssh access
  hetzner.hcloud.hcloud_firewall:
    name: ssh
    api_token: "{{ hcloud_token }}"
    rules:
      - direction: in
        protocol: icmp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow icmp in
      - direction: in
        protocol: tcp
        port: "22"
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow icmp in
    state: present
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-firewalls

- name: Create a firewall for web access
  hetzner.hcloud.hcloud_firewall:
    name: web
    api_token: "{{ hcloud_token }}"
    rules:
      - direction: in
        protocol: icmp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow icmp in
      - direction: in
        protocol: tcp
        port: "80"
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow https in
      - direction: in
        protocol: tcp
        port: "443"
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow https in
    state: present
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-firewalls

- name: Create a firewall for no incoming access
  hetzner.hcloud.hcloud_firewall:
    name: closed
    api_token: "{{ hcloud_token }}"
    rules: []
    state: present
  delegate_to: localhost
  tags:
    - hetzner
    - hetzner-firewalls
