when:
  - event: pull_request
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  'ansible (check)':
    when:
      event: [pull_request]
    image: woodpeckerci/plugin-ansible:0.2.1
    pull: true
    environment:
      ANSIBLE_ROLES_PATH: ./roles
    settings:
      playbook: site.yaml
      diff: true
      galaxy: requirements.yaml
      inventory: inventory
      syntax_check: false
      become: true
      check: true
      user: root
      galaxy_force: false
      vault-password:
        from_secret: ansible_vault_password

  'ansible (apply)':
    when:
      - event: [manual]
        branch: ${CI_REPO_DEFAULT_BRANCH}
    image: woodpeckerci/plugin-ansible:0.2.1
    environment:
      ANSIBLE_ROLES_PATH: ./roles
    settings:
      playbook: site.yaml
      diff: true
      galaxy: requirements.yaml
      inventory: inventory
      syntax_check: false
      become: true
      check: false
      user: root
      galaxy_force: false
