when:
  - event: pull_request
  - event: [push, deployment]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: 'Install galaxy requirements'
    image: alpine:3.20
    commands:
      - apk add -q --no-cache ansible git
      - ansible-galaxy install -r requirements.yaml

  - name: ansible (check)
    image: woodpeckerci/plugin-ansible:1.0.6
    settings:
      playbook: playbooks/run.yaml
      diff: true
      inventory: inventory.yaml
      syntax_check: false
      become: true
      check: true
      user: root
      galaxy_force: false
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: ansible_ssh_private_key
    when:
      - event: pull_request
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}

  - name: ansible (apply)
    image: woodpeckerci/plugin-ansible:1.0.6
    settings:
      playbook: playbooks/run.yaml
      diff: true
      inventory: inventory.yaml
      syntax_check: false
      become: true
      check: false
      user: root
      galaxy_force: false
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: ansible_ssh_private_key
    when:
      - event: deployment
        branch: ${CI_REPO_DEFAULT_BRANCH}
