when:
  - event: pull_request
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  no-vault:
    image: bash
    commands:
      - sed -i '/vault_password_file/d' ansible.cfg
      - sed -i  's/vault\.yaml/vault\.example\.yaml/g' playbooks/run.yaml

  ansible-lint:
    image: pipelinecomponents/ansible-lint:0.71.0
    depends_on: no-vault
    commands:
      - ansible-galaxy install -r requirements.yaml
      - ansible-lint

  editor-config:
    image: mstruebing/editorconfig-checker:v3.0.1
    depends_on: []
