when:
  event: [pull_request, manual]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  no-vault:
    image: bash
    commands:
      - sed -i '/vault_password_file/d' ansible.cfg
      - sed -i  's/vault\.yaml/vault\.example\.yaml/g' site.yaml

  ansible-lint:
    image: pipelinecomponents/ansible-lint:0.65.0
    depends_on: no-vault
    commands:
      - ansible-galaxy install -r requirements.yaml
      - ansible-lint

  editor-config:
    image: mstruebing/editorconfig-checker:2.7.2
    depends_on: []
