when:
  - event: pull_request
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: no-vault
    image: docker.io/bash
    commands:
      - sed -i '/vault_password_file/d' ansible.cfg
      - sed -i  's/vault\.yaml/vault\.example\.yaml/g' playbooks/run.yaml

  - name: ansible-lint
    image: docker.io/pipelinecomponents/ansible-lint:0.79.0
    depends_on: no-vault
    environment:
      ANSIBLE_CONFIG: ansible.cfg
    commands:
      - ansible-galaxy install -r requirements.yaml
      - ansible-lint

  - name: editor-config
    image: docker.io/mstruebing/editorconfig-checker:v3.3.0
    depends_on: []
