when:
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  no-vault:
    image: bash
    commands:
      - sed -i '/vault_password_file/d' ansible.cfg
      - sed -i  's/vault\.yaml/vault\.example\.yaml/g' site.yaml

  ansible-lint:
    image: pipelinecomponents/ansible-lint:0.63.0
    depends_on: []
    commands:
      - ansible-galaxy install -r requirements.yaml
      - ansible-lint

  editor-config:
    image: mstruebing/editorconfig-checker:2.7.2
    depends_on: []
