when:
  event: cron
  cron: reboot

steps:
  - name: ansible-reboot
    image: docker.io/woodpeckerci/plugin-ansible:1.0.8
    settings:
      playbook: playbooks/reboot.yaml
      inventory: inventory.yaml
      become: true
      user: root
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: ansible_ssh_private_key
