- name: Woodpecker agent container
  community.docker.docker_container:
    container_name: woodpecker_agent
    hostname: woodpecker_agent
    pull: 'always'
    image: woodpeckerci/woodpecker-agent:{{ woodpecker_agent_version }}
    restart: 'always'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/woodpecker:/etc/woodpecker/
    env:
      WOODPECKER_SERVER: '{{ woodpecker_agent_server }}'
      WOODPECKER_AGENT_SECRET: '{{ woodpecker_agent_agent_secret }}'
      WOODPECKER_MAX_PROCS: '{{ woodpecker_agent_max_processes }}'
    networks:
      - web
      - default

  tags:
    - woodpecker
    - woodpecker-agent
